# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bread', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='food',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='calorie',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='food',
            name='calorie',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
