# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-26 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bread', '0003_user_calorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_calorie',
            name='exetr',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_calorie',
            name='foodtr',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
