# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-26 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bread', '0004_auto_20171027_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_calorie',
            name='exetr',
        ),
        migrations.RemoveField(
            model_name='user_calorie',
            name='foodtr',
        ),
    ]
